#####
## e.g. en.wikipedia.org/wiki/Guinea  etc.

gn: Guinea
gw: Guinea-Bissau
ke: Kenya
ls: Lesotho
lr: Liberia
mg: Madagascar
mw: Malawi
ml: Mali
mr: Mauritania
mu: Mauritius
mz: Mozambique
na: Namibia
ne: Niger
rw: Rwanda
st: São_Tomé_and_Príncipe
sn: Senegal
yc: Seychelles
sl: Sierra_Leone
so: Somalia
ss: South_Sudan
sd: Sudan
sz: Swaziland
tg: Togo
ug: Uganda
tz: Tanzania
zm: Zambia
zw: Zimbabwe
